### PR TITLE
Implemented new art for card chances.

### PR DESCRIPTION
**Pull request by zachwlewis**
Added themed frames for draw and holding chances.

hdt-chance-frame

### CODE REVIEW

**Comment by Cu8eR** [comment]
Nice, really nice!

**Comment by zachwlewis** [comment]
Also updated the card counter. I'm still working on getting these new assets into the individual windows, so don't merge yet.

hdt-skinned-card-frames

**Comment by zachwlewis** [comment]
Alrighty. I slimmed down the frames and I added them to the Player and Opponent windows. I also increased the width of those windows slightly to give the elements room to breathe.

We should be good to pull! :shipit: 

hdt-slim-card-frames

**Comment by Epix37** [comment]
10/10 !

**Pull request merged**
