### PR TITLE
fix bug about gold tracking

### PR DESCRIPTION
**Pull request by chucklu**
Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Windows\OverlayWindow.xaml.cs
private void UpdateGoldProgress()
        {
            var region = (int)_game.CurrentRegion - 1;
            if (region >= 0)
            {
                LblGoldProgress.Text = string.Format("Wins: {0}/3 ({1}/100G)", Config.Instance.GoldProgress[region],
                                                     Config.Instance.GoldProgressTotal[region]);
            }
        }

when _game.CurrentRegion is China 
  var region = (int)_game.CurrentRegion - 1;
region ==5-1=4

then the index region is out of GoldProgress and GoldProgressTotal,the same as GoldProgressLastReset

### CODE REVIEW

**Comment by chucklu** [comment]
Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\HsLogReader.cs
if(int.TryParse(rawWins, out wins))
						{
							TimeZoneInfo timeZone = null;
							switch(Game.CurrentRegion)
							{
								case Region.EU:
									timeZone = TimeZoneInfo.FindSystemTimeZoneById("Central European Standard Time");
									break;
								case Region.US:
									timeZone = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
									break;
								case Region.ASIA:
									timeZone = TimeZoneInfo.FindSystemTimeZoneById("Korea Standard Time");
									break;
							}
}

Maybe I should do something more

**Comment by chucklu** [comment]
I think ,that's it.

When you release next version,pls remember update the config.xml for user cause the  GoldProgress and GoldProgressTotal,GoldProgressLastReset 
size changed from 3 to 5

**Comment by chucklu** [comment]
Almost forget this:Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\HsLogReader.cs
I have not modified the code in last 2 commits,cause I find the code in this file is not executed.

**Comment by Epix37** [comment]
HSLogReader.cs is no longer used. Changes need to be applies to LogReader/HSLogReaderV2.cs

**Comment by chucklu** [comment]
Ok,I have applied the code to  LogReader/HSLogReaderV2.cs
you can check the pull request

**Comment by Epix37** [comment]
The array size seems to update fine on it's own.

Changes work nicely - the wording on `At least {2} wins did not get gold reward` may need some simplification? I'm not really sure what to change it to though...

**Comment by chucklu** [comment]
you mean,when you release next version,the program will reset the array size itself?

At least {2} wins did not get gold reward
I am a Chinese，I don't know how to simplified this info.
If you can simplified this,just do it.

**Comment by chucklu** [comment]
else
                {
                    LblGoldProgress.Text = string.Format("At least {2} wins did not get gold reward , Wins: {0}/3 ({1}/100G) , ",
                        wins,
                        Config.Instance.GoldProgressTotal[region], wins - 2);
                }
If we don't notify the users,they may tell this situation by themselves
just use this info   Wins: {0}/3 ({1}/100G)

like this Wins: 5/3 (40/100G)
the users may understand why this happened

**Comment by chucklu** [comment]
HSLogReader.cs is no longer used
I wonder why we still kept this file in the project

**Pull request merged**
