### PR TITLE
Gave the news bar some much needed whitespace.

### PR DESCRIPTION
**Pull request by zachwlewis**
The news bar has always felt really cramped. This helps out.

### CODE REVIEW

**Comment by Epix37** [comment]
Mmmh... how about 24? This feels a bit too big.

**Comment by zachwlewis** [comment]
You could try it. I might submit another pull request if it's still too tight. :sweat_smile:

**Comment by Epix37** [comment]
Try it and tell me what you think, that's why I asked :P.

**Comment by zachwlewis** [comment]
Fine. I'll do all the work. :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
