### PR TITLE
Add icon for board attack, change default position

### PR DESCRIPTION
**Pull request by andburn**
Moved the default icon position to the other side of the board. I left the same positioning scheme so it can still be moved when the overlay is unlocked. As you mentioned, that does leave the side effect that it will move with different widths, but I think its good that it can be moved around.

### CODE REVIEW

**Comment by Epix37** [comment]
They can already be moved around freely by unlocking the overlay :).

What aspect ratio are the new values based on?
If they are not, coud you make them 4:3 and modify the [`Canvas.SetLeft`](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Windows/OverlayWindow.xaml.cs#L614) to use 
```C#
DeckExporter.GetXPos(Config.Instance.AttackIconPlayerHorizontalPosition / 100, (int)Width, ratio)
``` 
 (and the opp respectively)?

**Comment by Epix37** [comment]
Nvm, done :). Thank you for the PRs!

**Comment by andburn** [comment]
Sorry, am AFK. The thing that was throwing me with the position was how the unlocking/moving [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Windows/OverlayWindow.xaml.cs#L302) was affected.

**Comment by Epix37** [comment]
Good catch! Fixed that.

**Pull request merged**
