### PR TITLE
Improve the readme's help screenshot

### PR DESCRIPTION
**Pull request by Tenchi2xh**
The current readme's help screenshot shows an old version of the app that didn't have the fancy UI elements yet. I did a new screenshot from the newest version and added some help popups on it, trying to mimick Hearthstone's look and feel. I tried to keep things simple, and didn't duplicate elements that have a similar icon (i.e. the player's drawing probabilities has the same icon as the opponent's).

The new help screenshot

### CODE REVIEW

**Comment by ThePsionic** [comment]
Opponent is misspelled on the left side at the probabilities.

**Comment by ThePsionic** [comment]
On the right side, at the own player's deck, "Card left" should probably be "Card*s* left".

**Comment by Tenchi2xh** [comment]
Thanks! Corrected :)

**Comment by DavidBPCode** [comment]
Fantastic upgrade!

**Comment by Tenchi2xh** [comment]
@daveenguyen @DavidBPCode Thanks :)

**Comment by Epix37** [comment]
Indeed very nice! I also the screenshot also to the [overlay wiki](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Overlay) and as a link behind the small overlay image on [hsdecktracker.net](http://hsdecktracker.net/).

**Pull request merged**
