### PR TITLE
Improve board attack calculation

### LINKED ISSUE #1614: Damage counter counts unspawned tokens from Soul of the Forest
Repro: Play some minions, cast Soul of the Forest. The damage counter for your board shows the combined damage of the minions on the board and the treants that will spawn from them.

Meaning if you had three minions out with 8 combined damage, after playing Soul of the Forest the counter now shows 14.

### PR DESCRIPTION
**Pull request by andburn**
Debug Window:
- fixed the Cards tabs treeview so it saves the expanded collapsed state
- add a damage tab to the debug window, to show the board damage info

Board attack calculation (fixes #1614, #1648, #1607, #1598)
- takes into accout windfury and charge
- only counts minions/weapons able to attack on your turn
- fixes problems with druid "choice" cards and polymorph
- damage icon text goes green when the board kills the other player (doesn't take taunts into account)
- scaled damage icon with height so is smaller at lower resolutions
- change card tooltip zindex so its above icons

Missed the release :disappointed:, stupid windfury weapons caused me so many problems :smile:

### CODE REVIEW

**Comment by Epix37** [comment]
The fix seems to be working very well, but all tests in BoardStateTest seem to be failing unless I add `Core.Game = new GameV2();` to the TestInitialize and run them one by one.

**Comment by andburn** [comment]
Damn, must've missed those tests after my last change. Fixed now.

**Comment by andburn** [comment]
Hardcoded a special case for V07TRON, I think it should work ok. Got rid of the green text too.

**Comment by Epix37** [comment]
Looks good :).

**Pull request merged**
