### PR TITLE
String Comparison Clean-up

### PR DESCRIPTION
**Pull request by Jecoms**
Cleaned up string comparisons to use the safer .Equals or
string.IsNullOrWhitespace().

### CODE REVIEW

**Comment by Jecoms** [comment]
Other suggestions I have would be to implement more enums when referencing titles from a set. i.e. The different card sets are referenced by their string name instead of an enum.

**Comment by Epix37** [comment]
`string` is a special case when it comes to the  `==` operator, if both sides are of type `string`, it always resolves to `Equals`. 

Besides that, using `str.Equals(str2)` is vulnerable to throw NullReferenceExceptions. The "safe" way to do it would be to use `string.Equals(str1, str2)`, but that is *exactly* what the `==` operator does with two strings.

**Comment by Epix37** [comment]
You can find the HearthDb library here: https://github.com/HearthSim/HearthDb

[CardSet](https://github.com/HearthSim/HearthDb/blob/master/HearthDb/Enums/CardSet.cs) has no names that are of any help, but HDT has `HearthDbConverter.SetConverter` method that turns those into the proper strings.

**Comment by Jecoms** [comment]
Ah. That was my Java bleeding through. I suppose I should have realized it wouldn't be an issue since you don't use the String object class. Another reason to like C# more!

I'll look into contributing more meaningful code after I've spent more time in it.

**Pull request closed without merging**
