### PR TITLE
only Brawl, Casual and Ranked game mode will count gold progress

### PR DESCRIPTION
**Pull request by chucklu**
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1456
fix bug reported by this issue

Maybe, we should close this issue https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1278  at the same time.

### CODE REVIEW

**Comment by Epix37** [comment]
Does this work reliably? The game mode is often determined after the game has ended.

**Comment by chucklu** [comment]
sorry,I have not tested this fix,I check when the gamemode get the value

**Comment by chucklu** [comment]
I don't have time to test this today,maybe I can do the test later

**Comment by chucklu** [comment]
ok,I have checked this function.
When I won a game in Arena mode,gold track avoid to count gold reward.

**Comment by Epix37** [comment]
Sorry I wasn't quite clear what I mean. The problem isn't that it would track in arena, as game mode in that case is either `Arena` or `None`, but in the other modes (which might be `None` at the time of the check) .

**Comment by chucklu** [comment]
ok,I debug this gold track procedure, actually the game mode is none when we count the gold reward.
we need to count the gold reward after the game mode detected？

**Comment by Epix37** [comment]
I think I fixed it locally now with mode detection. Still need to test later.

**Comment by chucklu** [comment]
ok,you can fix this by yourself.
I was confused by the game mode detection

**Pull request closed without merging**
